general:
  random_bool: false
  seed_id: 2907
  dimensions: 2
grid:
  loc_hp: # Location of the heatpump in metres
  - 50
  - 120
  - 1
  ncells:
  - 20
  - 256
  - 1
  size:
  - 100
  - 1280
  - 0
permeability:
  case: perlin_v2
  factor: 40
  frequency:
  - 9
  - 9
  perm_max: 6.65e-09
  perm_min: 1.36e-12