general:
  random_bool: True
  seed_id: 2907
  dimensions: 2
grid:
  distance_to_border: 
  - 10
  - 10
  - 1
  ncells: automatic
  refinement: False
  resolution: 5 #0.3125 #[m]
  size [m]:
  - 640
  - 320
  loc_hp [m]:
  - 111
  - 161
  - 1