general:
  random_bool: True
  seed_id: 2907
  dimensions: 2
grid:
  distance_to_border: 20
  ncells: automatic
  refinement: True
  resolution: 5 #[m]
  size [m]:
  - 640
  - 320
  loc_hp [m]:
  - 161
  - 111
  - 1