general:
  random_bool: false
  seed_id: 2907
  dimensions: 2
grid:
  loc_hp: # Location of the heatpump in metres
  - 320
  - 320
  - 1
  ncells:
  - 128
  - 128
  - 1
  size:
  - 640
  - 640
  - 0
permeability:
  case: perlin_v2
  factor: 40
  frequency:
  - 0.9
  - 0.9
  max: 5.09683995922528e-09   #testcases #old:6.65e-09
  min: 1.0193679918450561e-11 #testcases #old:1.36e-12
pressure:
  case: perlin_v2
  factor: 40
  frequency:
  - 0.9
  - 0.9
  max: -0.0015
  min: -0.0035
injection:
  temperature: 15.6
  rate: 0.00024