general:
  random_bool: false
  seed_id: 2907
  dimensions: 2
grid:
  loc_hp: # Location of the heatpump in metres
  - 200
  - 120
  - 1
  distance_to_border:
  - - 575 # [m] x both
  - - 100 # [m] y lower
    - 1165 # [m] y upper
  - 0
  ncells:
  - 2000
  - 2000
  - 1
  size:
  - 10000
  - 10000
  - 0
permeability:
  case: perlin_v2
  factor: 40
  frequency:
  - 4
  - 8
  perm_max: 3.0e-10 #5.09683995922528e-09 #testcases   #old:6.65e-09
  perm_min: 1.e-11 #1.0193679918450561e-11 #testcases #old:1.36e-12