general:
  random_bool: false
  seed_id: 2907
grid:
  loc_hp: # Location of the heatpump in metres
  - 50
  - 80
  - 50
  ncells:
  - 20
  - 80
  - 16
  size:
  - 100
  - 400
  - 80
permeability:
  case: perlin_noise
  factor: 40
  frequency:
  - 2 #10
  - 8 #10
  - 2 #2
  perm_max: 6.65e-09
  perm_min: 1.36e-12