general:
  random_bool: false
  seed_id: 2907
grid:
  loc_hp: # Location of the heatpump in metres
  - 50
  - 120
  - 50
  ncells:
  - 20
  - 256
  - 1
  size:
  - 100
  - 1280
  - 80
  faceArea: 1
permeability:
  case: perlin_noise
  factor: 40
  frequency:
  - 2
  - 6
  - 2
  perm_max: 6.65e-09
  perm_min: 1.36e-12