general:
  random_bool: false
  seed_id: 2907
grid:
  faceArea: 1
  loc_hp:
  - 50
  - 120
  - 50
  ncells:
  - 10
  - 128
  - 8
  size:
  - 100
  - 1280
  - 80
permeability:
  case: perlin_noise
  factor: 40
  frequency:
  - 2
  - 6
  - 2
  perm_max: 6.65e-09
  perm_min: 1.36e-12
