general:
  random_bool: false
  seed_id: 2907
  dimensions: 2
grid:
  loc_hp: # Location of the heatpump in metres
  - 200
  - 120
  - 1
  distance_to_border_in_cells:
  - 20
  - 128
  - 0
  ncells:
  - 160 #320
  - 256 #512
  - 1
  size:
  - 1600
  - 2560
  - 0
permeability:
  case: perlin_v2
  factor: 40
  frequency:
  - 2
  - 4
  perm_max: 5.09683995922528e-09 #testcases   #old:6.65e-09
  perm_min: 1.0193679918450561e-11 #testcases #old:1.36e-12